# Generated by Django 4.2 on 2025-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMarket',
            fields=[
                ('market_ID', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('area_num', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('worker_num', models.IntegerField()),
            ],
        ),
    ]
