# Generated by Django 4.2 on 2025-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_ID', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=300)),
                ('register_date', models.DateField()),
                ('customer_num', models.IntegerField()),
            ],
        ),
    ]
