# Generated by Django 4.2 on 2025-02-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_ID', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=300)),
                ('goods_price', models.IntegerField()),
                ('goods_stock', models.IntegerField()),
                ('market_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main_market.mainmarket')),
            ],
        ),
    ]
